-- 코드를 입력하세요
-- 2022 1월 도서 판메 데이터
-- 저자, 카테고리 groupby 매출출액
SELECT a.AUTHOR_ID,
    a.AUTHOR_NAME,
    CATEGORY,
    SUM(SALES * PRICE) AS SALES
FROM BOOK b
JOIN AUTHOR a
    ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN BOOK_SALES bs
    on b.BOOK_ID = bs.BOOK_ID
WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'
GROUP BY a.AUTHOR_ID, a.AUTHOR_NAME, CATEGORY
ORDER BY a.AUTHOR_ID ASC,
    CATEGORY DESC
