SELECT
    ID,
    CASE
        WHEN PERCENT <= 0.25 THEN 'CRITICAL'
        WHEN PERCENT <= 0.50 THEN 'HIGH'
        WHEN PERCENT <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM
    (SELECT
        ID,
        PERCENT_RANK() over (ORDER BY SIZE_OF_COLONY DESC) AS PERCENT
    FROM
        ECOLI_DATA) e
ORDER BY
    ID