SELECT
    ri.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(avg(REVIEW_SCORE), 2) as SCORE
FROM
    REST_INFO ri
    JOIN REST_REVIEW  rr on ri.REST_ID = rr.REST_ID
WHERE
    ADDRESS LIKE '서울%'
GROUP BY 
    ri.REST_ID
ORDER BY
    SCORE DESC,
    FAVORITES DESC