-- 코드를 입력하세요
SELECT 
    USER_ID,
    NICKNAME,
    SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD a
JOIN USED_GOODS_USER  b
    on a.WRITER_ID = b.USER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC