SELECT
    USER_ID,
    NICKNAME,
    SUM(PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_USER u
    JOIN USED_GOODS_BOARD b on u.USER_ID = b.WRITER_ID
WHERE
    STATUS = 'DONE'
GROUP BY
    USER_ID
    HAVING
        SUM(PRICE) >= 700000
ORDER BY
    SUM(PRICE)