SELECT
    YEAR,
    MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM
    ECOLI_DATA
    JOIN (
        SELECT
            YEAR(DIFFERENTIATION_DATE) AS YEAR,
            MAX(SIZE_OF_COLONY) AS MAX_SIZE
        FROM
            ECOLI_DATA 
        GROUP BY
            YEAR(DIFFERENTIATION_DATE)
    ) as m ON DATE_FORMAT(DIFFERENTIATION_DATE, '%Y') = m.YEAR
ORDER BY
    YEAR ASC,
    YEAR_DEV ASC