SELECT
    TITLE,
    ugb.BOARD_ID,
    REPLY_ID,
    ugr.WRITER_ID,
    ugr.CONTENTS,
    DATE_FORMAT(ugr.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM
    USED_GOODS_BOARD ugb
    JOIN USED_GOODS_REPLY ugr ON ugb.BOARD_ID = ugr.BOARD_ID
WHERE
    DATE_FORMAT(ugb.CREATED_DATE, '%Y%m') = '202210'
ORDER BY
    CREATED_DATE ASC,
    TITLE ASC