SELECT
    TITLE,
    ugb.BOARD_ID,
    REPLY_ID,
    ugr.WRITER_ID,
    ugr.CONTENTS,
    TO_CHAR(ugr.CREATED_DATE, 'YYYY-MM-DD') as CREATED_DATE
FROM
    USED_GOODS_BOARD ugb
    JOIN USED_GOODS_REPLY ugr on ugb.BOARD_ID = ugr.BOARD_ID
WHERE
    TO_CHAR(ugb.CREATED_DATE, 'YYYYMM') = '202210'
ORDER BY
    ugr.CREATED_DATE,
    TITLE