-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK a
JOIN BOOK_SALES b
    on a.BOOK_ID = b.BOOK_ID 
WHERE TO_CHAR(b.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY a.CATEGORY
ORDER BY a.CATEGORY ASC