SELECT
    CATEGORY,
    SUM(SALES) AS TOTAL_SALES
FROM
    BOOK b
    JOIN BOOK_SALES s on b.BOOK_ID = s.BOOK_ID
WHERE
    DATE_FORMAT(SALES_DATE, '%Y%m') = '202201'
GROUP BY
    CATEGORY
ORDER BY
    CATEGORY ASC